### GET request to example server
GET http://localhost:8080/test/1

###

POST http://localhost:8080/test
Content-Type: application/json

{
  "id": 1,
  "title": "Test Title",
  "content": "Test Content"
}